-- MySQL Script generated by MySQL Workbench
-- qua 05 ago 2020 22:54:37
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cotacoes_Bovespa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cotacoes_Bovespa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cotacoes_Bovespa` ;
USE `cotacoes_Bovespa` ;

-- -----------------------------------------------------
-- Table `cotacoes_Bovespa`.`Empresas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cotacoes_Bovespa`.`Empresas` ;

CREATE TABLE IF NOT EXISTS `cotacoes_Bovespa`.`Empresas` (
  `idEmpresas` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Code` VARCHAR(45) NULL,
  PRIMARY KEY (`idEmpresas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cotacoes_Bovespa`.`TPMerc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cotacoes_Bovespa`.`TPMerc` ;

CREATE TABLE IF NOT EXISTS `cotacoes_Bovespa`.`TPMerc` (
  `Id_TPMerc` INT NOT NULL,
  `Description` VARCHAR(45) NULL,
  `Code` VARCHAR(45) NULL,
  PRIMARY KEY (`Id_TPMerc`))
ENGINE = InnoDB
COMMENT = 'RELAÇÃO DOS VALORES PARA TIPO DE\nMERCADO';


-- -----------------------------------------------------
-- Table `cotacoes_Bovespa`.`INDOPC`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cotacoes_Bovespa`.`INDOPC` ;

CREATE TABLE IF NOT EXISTS `cotacoes_Bovespa`.`INDOPC` (
  `id_INDOPC` INT NOT NULL,
  `Code_Number` INT NULL,
  `Code_Text` VARCHAR(45) NULL,
  `Description` VARCHAR(45) NULL,
  PRIMARY KEY (`id_INDOPC`))
ENGINE = InnoDB
COMMENT = 'RELAÇÃO DOS VALORES PARA CORREÇÃO DE CONTRATOS';


-- -----------------------------------------------------
-- Table `cotacoes_Bovespa`.`ESPECI`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cotacoes_Bovespa`.`ESPECI` ;

CREATE TABLE IF NOT EXISTS `cotacoes_Bovespa`.`ESPECI` (
  `idESPECI` INT NOT NULL,
  `Code` VARCHAR(45) NULL,
  `Description` VARCHAR(45) NULL,
  PRIMARY KEY (`idESPECI`))
ENGINE = InnoDB
COMMENT = 'RELAÇÃO DE VALORES PARA ESPECIFICAÇÃO';


-- -----------------------------------------------------
-- Table `cotacoes_Bovespa`.`CODBDI`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cotacoes_Bovespa`.`CODBDI` ;

CREATE TABLE IF NOT EXISTS `cotacoes_Bovespa`.`CODBDI` (
  `idCODBDI` INT NOT NULL,
  `Code` INT NULL,
  `Description` VARCHAR(45) NULL,
  PRIMARY KEY (`idCODBDI`))
ENGINE = InnoDB
COMMENT = 'RELAÇÃO DOS VALORES PARA CÓDIGOS DE BDI';


-- -----------------------------------------------------
-- Table `cotacoes_Bovespa`.`CODNEG`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cotacoes_Bovespa`.`CODNEG` ;

CREATE TABLE IF NOT EXISTS `cotacoes_Bovespa`.`CODNEG` (
  `idCODNEG` INT NOT NULL,
  `Empresa_ID` INT NULL,
  `Code` VARCHAR(45) NULL,
  PRIMARY KEY (`idCODNEG`),
  INDEX `Empresa_Id_idx` (`Empresa_ID` ASC) VISIBLE,
  CONSTRAINT `Empresa_Id`
    FOREIGN KEY (`Empresa_ID`)
    REFERENCES `cotacoes_Bovespa`.`Empresas` (`idEmpresas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Codigo de Negociação da empresa';


-- -----------------------------------------------------
-- Table `cotacoes_Bovespa`.`Cotacoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cotacoes_Bovespa`.`Cotacoes` ;

CREATE TABLE IF NOT EXISTS `cotacoes_Bovespa`.`Cotacoes` (
  `idCotacoes` INT NOT NULL,
  `Date_Pregao` DATE NULL,
  `CODBDI_ID` INT NULL,
  `CODNEG_ID` INT NULL,
  `TPMerc_Id` INT NULL,
  `ESPECI_Id` INT NULL,
  `Prazot` VARCHAR(45) NULL COMMENT 'PRAZO EM DIAS DO MERCADO A TERMO',
  `MODREF` VARCHAR(45) NULL COMMENT 'MOEDA USADA NA DATA DO PREGÃO',
  `PREABRE` DECIMAL(20,2) NULL COMMENT 'PREÇO DE ABERTURA DO PAPEL-MERCADO NO PREGÃO',
  `PREMAX` DECIMAL(20,2) NULL COMMENT 'PREÇO MÁXIMO DO PAPEL-MERCADO NO PREGÃO',
  `PREMIN` DECIMAL(20,2) NULL,
  `PREMED` DECIMAL(20,2) NULL,
  `PREULT` DECIMAL(20,2) NULL,
  `PREOFC` DECIMAL(20,2) NULL,
  `PREOFV` DECIMAL(20,2) NULL,
  `TETONEG` INT NULL,
  `QUATOT` INT NULL,
  `VOLTOT` INT NULL,
  `PREEXE` DECIMAL(20,2) NULL,
  `INDOPC_ID` INT NULL,
  `DATEVEN` DATE NULL,
  `FATCOT` VARCHAR(45) NULL COMMENT 'FATOR DE COTAÇÃO DO PAPEL\n\n‘1’ = COTAÇÃO UNITÁRIA\n‘1000’ = COTAÇÃO POR LOTE DE MIL AÇÕES',
  `PTOEXE` VARCHAR(45) NULL,
  `CODISI` VARCHAR(45) NULL,
  `DISMES` VARCHAR(45) NULL,
  PRIMARY KEY (`idCotacoes`),
  INDEX `CODBDI_idx` (`CODBDI_ID` ASC) VISIBLE,
  INDEX `TPMercID_idx` (`TPMerc_Id` ASC) VISIBLE,
  INDEX `CODNEG_ID_idx` (`CODNEG_ID` ASC) VISIBLE,
  INDEX `ESPECI_ID_idx` (`ESPECI_Id` ASC) VISIBLE,
  INDEX `INDOPC_ID_idx` (`INDOPC_ID` ASC) VISIBLE,
  CONSTRAINT `CODBDI`
    FOREIGN KEY (`CODBDI_ID`)
    REFERENCES `cotacoes_Bovespa`.`CODBDI` (`idCODBDI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CODNEG_ID`
    FOREIGN KEY (`CODNEG_ID`)
    REFERENCES `cotacoes_Bovespa`.`CODNEG` (`idCODNEG`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `TPMercID`
    FOREIGN KEY (`TPMerc_Id`)
    REFERENCES `cotacoes_Bovespa`.`TPMerc` (`Id_TPMerc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ESPECI_ID`
    FOREIGN KEY (`ESPECI_Id`)
    REFERENCES `cotacoes_Bovespa`.`ESPECI` (`idESPECI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `INDOPC_ID`
    FOREIGN KEY (`INDOPC_ID`)
    REFERENCES `cotacoes_Bovespa`.`INDOPC` (`id_INDOPC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
